- alias: llama3:instruct
  family: llama3
  repo: QuantFactory/Meta-Llama-3-8B-Instruct-GGUF
  filename: Meta-Llama-3-8B-Instruct.Q8_0.gguf
  features:
    - chat
  chat_template: llama3
- alias: llama3:70b-instruct
  family: llama3
  repo: QuantFactory/Meta-Llama-3-70B-Instruct-GGUF
  filename: Meta-Llama-3-70B-Instruct.Q4_0.gguf
  features:
    - chat
  chat_template: llama3
- alias: llama2:chat
  family: llama2
  repo: TheBloke/Llama-2-7B-Chat-GGUF
  filename: llama-2-7b-chat.Q8_0.gguf
  features:
    - chat
  chat_template: llama2
- alias: llama2:13b-chat
  family: llama2
  repo: TheBloke/Llama-2-13B-chat-GGUF
  filename: llama-2-13b-chat.Q8_0.gguf
  features:
    - chat
  chat_template: llama2
- alias: llama2:70b-chat
  family: llama2
  repo: TheBloke/Llama-2-70B-Chat-GGUF
  filename: llama-2-70b-chat.Q4_0.gguf
  features:
    - chat
  chat_template: llama2
- alias: phi3:mini
  family: phi3
  repo: microsoft/Phi-3-mini-4k-instruct-gguf
  filename: Phi-3-mini-4k-instruct-fp16.gguf
  features:
    - chat
  chat_template: phi3
- alias: mistral:instruct
  family: mistral
  repo: MaziyarPanahi/Mistral-7B-Instruct-v0.3-GGUF
  filename: Mistral-7B-Instruct-v0.3.Q8_0.gguf
  features:
    - chat
  chat_template: llama2-legacy
- alias: mixtral:instruct
  family: mixtral
  repo: TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF
  filename: mixtral-8x7b-instruct-v0.1.Q8_0.gguf
  features:
    - chat
  chat_template: llama2-legacy
- alias: gemma:instruct
  family: gemma
  repo: google/gemma-7b-it-GGUF
  filename: gemma-7b-it.gguf
  features:
    - chat
  chat_template: gemma
- alias: gemma:7b-instruct-v1.1-q8_0
  family: gemma
  repo: google/gemma-1.1-7b-it-GGUF
  filename: 7b_it_v1p1.gguf
  features:
    - chat
  chat_template: gemma
