import { ModelCatalog } from './model-catalog-types';

export const chatModelsCatalog: ModelCatalog[] = [
  {
    id: 'qwen3.5-35b-a3b',
    name: 'Qwen3.5 35B-A3B',
    repo: 'unsloth/Qwen3.5-35B-A3B-GGUF',
    filename: 'Qwen3.5-35B-A3B-Q4_K_M.gguf',
    quantization: 'Q4_K_M',
    size: '22GB',
    parameters: '35B (3B active)',
    category: 'chat',
    tier: 'premium',
    badge: '⭐ Best Overall',
    ratings: { quality: 5, speed: 4.5, specialization: 5 },
    benchmarks: {},
    contextWindow: '262K',
    memoryEstimate: '~22GB',
    license: 'Apache 2.0',
    licenseUrl: 'https://huggingface.co/unsloth/Qwen3.5-35B-A3B-GGUF',
    tooltipContent: {
      strengths: ['MoE architecture (3B active of 35B)', 'Beats GPT-OSS-120B on GPQA Diamond', 'Natively multimodal'],
      useCase: 'Best all-around model for general tasks with excellent efficiency',
      researchNotes:
        "Alibaba's Feb 2026 flagship MoE. 262K context. Outperforms models 13x its size on key benchmarks.",
    },
  },
  {
    id: 'qwen3.5-27b',
    name: 'Qwen3.5 27B',
    repo: 'unsloth/Qwen3.5-27B-GGUF',
    filename: 'Qwen3.5-27B-Q4_K_M.gguf',
    quantization: 'Q4_K_M',
    size: '16.7GB',
    parameters: '27B',
    category: 'chat',
    tier: 'premium',
    badge: '⭐ Best Dense',
    ratings: { quality: 5, speed: 4, specialization: 5 },
    benchmarks: {},
    contextWindow: '262K',
    memoryEstimate: '~16.7GB',
    license: 'Apache 2.0',
    licenseUrl: 'https://huggingface.co/unsloth/Qwen3.5-27B-GGUF',
    tooltipContent: {
      strengths: [
        'Dense architecture — all 27B params active',
        'Highest per-token reasoning density',
        '262K context window',
      ],
      useCase: 'Deep reasoning tasks where every parameter contributes — math, coding, analysis',
      researchNotes:
        'Feb 2026. Dense model complements MoE variants. Major upgrade from Qwen3-32B with smaller footprint.',
    },
  },
  {
    id: 'phi-4-reasoning',
    name: 'Phi-4 Reasoning',
    repo: 'bartowski/microsoft_Phi-4-reasoning-GGUF',
    filename: 'Phi-4-reasoning-Q8_0.gguf',
    quantization: 'Q8_0',
    size: '15.6GB',
    parameters: '14B',
    category: 'chat',
    tier: 'premium',
    badge: '⭐ Best Reasoning',
    ratings: { quality: 5, speed: 4, specialization: 5 },
    benchmarks: {},
    contextWindow: '16K',
    memoryEstimate: '~15.6GB',
    license: 'MIT',
    licenseUrl: 'https://huggingface.co/bartowski/microsoft_Phi-4-reasoning-GGUF',
    tooltipContent: {
      strengths: ['Most robust reasoning model', 'Competes with 5-50x larger models', 'Exceptional math capabilities'],
      useCase: 'Ideal for complex reasoning, mathematical problems, and tasks requiring consistency',
      researchNotes: "Microsoft's reasoning-optimized SLM. 82.2% robustness on linguistic variation tests.",
    },
  },
  {
    id: 'qwen3.5-9b',
    name: 'Qwen3.5 9B',
    repo: 'unsloth/Qwen3.5-9B-GGUF',
    filename: 'Qwen3.5-9B-Q8_0.gguf',
    quantization: 'Q8_0',
    size: '9.5GB',
    parameters: '9B',
    category: 'chat',
    tier: 'specialized',
    badge: 'Best Value',
    ratings: { quality: 4.5, speed: 5, specialization: 4.5 },
    benchmarks: { humanEval: 81.7 },
    contextWindow: '262K',
    memoryEstimate: '~9.5GB',
    license: 'Apache 2.0',
    licenseUrl: 'https://huggingface.co/unsloth/Qwen3.5-9B-GGUF',
    tooltipContent: {
      strengths: [
        'Beats previous-gen 30B models',
        'Matches GPT-OSS-120B on GPQA Diamond (81.7)',
        'Natively multimodal',
      ],
      useCase: 'Fast inference, running multiple models, or resource-constrained setups',
      researchNotes: 'Mar 2026 small series. 9B params that outperform models 13x larger. 262K context.',
    },
  },
  {
    id: 'glm-4.7-flash',
    name: 'GLM-4.7 Flash',
    repo: 'ggml-org/GLM-4.7-Flash-GGUF',
    filename: 'GLM-4.7-Flash-Q4_K_M.gguf',
    quantization: 'Q4_K_M',
    size: '18.1GB',
    parameters: '30B (3.6B active)',
    category: 'chat',
    tier: 'specialized',
    badge: 'Multimodal Latest',
    ratings: { quality: 4.5, speed: 4, specialization: 5 },
    benchmarks: {},
    contextWindow: '200K',
    memoryEstimate: '~18.1GB',
    license: 'Apache 2.0',
    licenseUrl: 'https://huggingface.co/ggml-org/GLM-4.7-Flash-GGUF',
    tooltipContent: {
      strengths: ['MoE 30B with 3.6B active params', '200K context with MLA', 'Native vision and tool calling'],
      useCase: 'Vision-language tasks, tool use, and agentic workflows',
      researchNotes: "Zhipu AI's Jan 2026 model. Successor to GLM-4.6V with 200K context and improved benchmarks.",
    },
  },
  {
    id: 'gemma-3-27b',
    name: 'Gemma 3 27B',
    repo: 'ggml-org/gemma-3-27b-it-GGUF',
    filename: 'gemma-3-27b-it-Q4_K_M.gguf',
    quantization: 'Q4_K_M',
    size: '16.5GB',
    parameters: '27B',
    category: 'chat',
    tier: 'specialized',
    badge: 'Google Multimodal',
    ratings: { quality: 4.5, speed: 4, specialization: 5 },
    benchmarks: {},
    contextWindow: '128K',
    memoryEstimate: '~16.5GB',
    license: 'Gemma License',
    licenseUrl: 'https://huggingface.co/ggml-org/gemma-3-27b-it-GGUF',
    tooltipContent: {
      strengths: [
        'Google QAT quantization (54% less quality loss)',
        'Native vision support',
        'Outperforms Gemini 1.5 Pro',
      ],
      useCase: 'Multimodal tasks with Google ecosystem. Strong alternative to Qwen for diverse vendor coverage.',
      researchNotes: 'Google DeepMind. QAT preserves near-BF16 quality at 3x less memory. 128K context.',
    },
  },
];

export const embeddingModelsCatalog: ModelCatalog[] = [
  {
    id: 'qwen3-embedding-8b',
    name: 'Qwen3 Embedding 8B',
    repo: 'Qwen/Qwen3-Embedding-8B-GGUF',
    filename: 'Qwen3-Embedding-8B-Q8_0.gguf',
    quantization: 'Q8_0',
    size: '8.05GB',
    parameters: '8B',
    category: 'embedding',
    tier: 'premium',
    badge: '⭐ Top Choice',
    ratings: { quality: 5, speed: 4, specialization: 5 },
    benchmarks: { mteb: 70.58 },
    contextWindow: '8K',
    memoryEstimate: '~8.05GB',
    license: 'Apache 2.0',
    licenseUrl: 'https://huggingface.co/Qwen/Qwen3-Embedding-8B-GGUF',
    tooltipContent: {
      strengths: ['#1 on MTEB multilingual leaderboard', '100+ languages', 'Upgraded from 4B'],
      useCase: 'Best overall embedding model for RAG applications and semantic search',
      researchNotes: '#1 MTEB multilingual (70.58 as of Jan 2026). Significant upgrade from 4B variant.',
    },
  },
  {
    id: 'bge-m3',
    name: 'BGE-M3',
    repo: 'gpustack/bge-m3-GGUF',
    filename: 'bge-m3-Q4_K_M.gguf',
    quantization: 'Q4_K_M',
    size: '438MB',
    parameters: '567M',
    category: 'embedding',
    tier: 'premium',
    badge: '⭐ Best Multilingual',
    ratings: { quality: 5, speed: 4, specialization: 5 },
    benchmarks: { mteb: 'Top Performer' },
    contextWindow: '8K',
    memoryEstimate: '~438MB',
    license: 'MIT',
    licenseUrl: 'https://huggingface.co/gpustack/bge-m3-GGUF',
    tooltipContent: {
      strengths: [
        'Best multilingual performance',
        'Supports 100+ languages',
        'Multi-functionality (dense, sparse, multi-vector)',
        '8K context window',
      ],
      useCase: 'Ideal for multilingual RAG applications and cross-lingual retrieval',
      researchNotes:
        'State-of-the-art multilingual embedding model from BAAI. Supports multi-functionality, multi-linguality, and multi-granularity with input sizes up to 8192 tokens.',
    },
  },
  {
    id: 'nomic-embed-v1.5',
    name: 'Nomic Embed v1.5',
    repo: 'nomic-ai/nomic-embed-text-v1.5-GGUF',
    filename: 'nomic-embed-text-v1.5.Q8_0.gguf',
    quantization: 'Q8_0',
    size: '274MB',
    parameters: '137M',
    category: 'embedding',
    tier: 'specialized',
    badge: 'Most Efficient',
    ratings: { quality: 4, speed: 5, specialization: 5 },
    benchmarks: {},
    contextWindow: '8K',
    memoryEstimate: '~274MB',
    license: 'Apache 2.0',
    licenseUrl: 'https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF',
    tooltipContent: {
      strengths: [
        'Ultra-small size (137M params)',
        'Matryoshka learning (64-768 dims)',
        'Excellent speed',
        '8K context',
      ],
      useCase: 'Best for resource-constrained scenarios and speed-critical applications',
      researchNotes:
        'Ranks similarly to top-10 MTEB models that are 70x bigger. Supports flexible embedding dimensions (64-768) for size/performance tradeoff. 86.2% top-5 accuracy.',
    },
  },
  {
    id: 'bge-large-en-v1.5',
    name: 'BGE Large EN v1.5',
    repo: 'mradermacher/bge-large-en-v1.5-GGUF',
    filename: 'bge-large-en-v1.5.Q4_K_M.gguf',
    quantization: 'Q4_K_M',
    size: '208MB',
    parameters: '335M',
    category: 'embedding',
    tier: 'specialized',
    badge: 'Strong English',
    ratings: { quality: 4.5, speed: 4.5, specialization: 5 },
    benchmarks: {},
    contextWindow: '512',
    memoryEstimate: '~208MB',
    license: 'MIT',
    licenseUrl: 'https://huggingface.co/mradermacher/bge-large-en-v1.5-GGUF',
    tooltipContent: {
      strengths: ['Excellent English performance', '1024 dimensions', 'Strong BAAI pedigree', '84.7% accuracy'],
      useCase: 'Optimal for English-only RAG applications requiring high accuracy',
      researchNotes:
        'Part of BAAI General Embedding (BGE) family. BGE edges ahead in raw accuracy (84.7%) and transforms text into 1024-dimensional vectors for dense retrieval.',
    },
  },
];
