name: setup-rust
description: setup rust and components
inputs:
  platform:
    description: "Platform to build for"
    required: true
  target:
    description: "Target to build for"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: install dependencies (ubuntu only)
      shell: bash
      if: inputs.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libwebkit2gtk-4.1-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf
    - uses: Swatinem/rust-cache@v2
    - name: install Rust 1.82.0
      uses: dtolnay/rust-toolchain@1.82.0
      with:
        targets: ${{ inputs.target }}
        components: rustfmt,clippy,llvm-tools
    - uses: taiki-e/install-action@cargo-llvm-cov
    - name: Install Tauri CLI (Windows)
      if: inputs.platform == 'windows-latest'
      shell: pwsh
      run: |
        if (-not (Get-Command cargo-tauri -ErrorAction SilentlyContinue)) {
          cargo install tauri-cli@^2.0.0
        }
    - name: Install Tauri CLI (Unix)
      if: inputs.platform != 'windows-latest'
      shell: bash
      run: |
        if ! command -v cargo-tauri > /dev/null 2>&1; then
          cargo install tauri-cli@^2.0.0
        fi
    - name: Update for deranged issue
      shell: bash
      run: |
        cargo update -p deranged
