name: setup-node
description: setup node and npm with caching
inputs:
  platform:
    description: "Platform to build for"
    required: true

runs:
  using: composite
  steps:
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/iron
        registry-url: 'https://registry.npmjs.org'

    - name: Get npm cache directory (Windows)
      if: inputs.platform == 'windows-latest'
      shell: pwsh
      run: echo "NPM_CACHE_DIR=$(npm config get cache)" >> $env:GITHUB_ENV

    - name: Get npm cache directory (Unix)
      if: inputs.platform != 'windows-latest'
      shell: bash
      run: echo "NPM_CACHE_DIR=$(npm config get cache)" >> $GITHUB_ENV

    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ${{ env.NPM_CACHE_DIR }}
        key: ${{ runner.os }}-npm-${{ hashFiles('crates/bodhi/package-lock.json', 'crates/lib_bodhiserver_napi/package-lock.json', 'ts-client/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install app npm dependencies (Windows)
      if: inputs.platform == 'windows-latest'
      shell: pwsh
      run: make -f Makefile.win.mk ci.app-pnpm

    - name: Install app npm dependencies (Unix)
      if: inputs.platform != 'windows-latest'
      shell: bash
      run: make ci.app-pnpm
