name: setup
description: sets up the repo for github actions

inputs:
  GH_PAT:
    description: Github token
    required: true
  platform:
    description: Platform to build for
    required: true

runs:
  using: composite
  steps:
    - name: Rewrite submodule URLs and checkout submodules
      shell: bash
      run: |
        git config --global url.https://gh_pat:${{ inputs.GH_PAT }}@github.com/.insteadOf git@github.com:
        git submodule sync --recursive
        git submodule update --init --recursive --depth=1
        git config --global --unset url.https://gh_pat:${{ inputs.GH_PAT }}@github.com/.insteadOf
    - uses: ./.github/actions/setup-rust
      with:
        platform: ${{ inputs.platform }}
    - uses: ./.github/actions/setup-node
