[workspace]
members = ["bodhiserver", "llama-server-bindings"]
resolver = "2"

[workspace.dependencies]
bindgen = "0.69.4"
cc = "1.0.90"

[profile.release.package.bodhiserver]
codegen-units = 1
strip = true
opt-level = 3
