name: setup-environment
description: Setup common environment configuration including git, submodules, and Python packages
inputs:
  platform:
    description: "Platform to build for"
    required: true
  gh-pat:
    description: "GitHub Personal Access Token for submodule access"
    required: true

runs:
  using: composite
  steps:
    - name: Set USER_HOME environment variable
      shell: bash
      run: |
        echo "USER_HOME=$HOME" >> $GITHUB_ENV

    - name: Enable symlinks and configure git
      shell: bash
      run: |
        git config --global core.symlinks true
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Rewrite submodule URLs and checkout submodules
      shell: bash
      run: |
        git config --global url.https://gh_pat:${{ inputs.gh-pat }}@github.com/.insteadOf git@github.com:
        git submodule sync --recursive
        git submodule update --init --recursive --depth=1
        git config --global --unset url.https://gh_pat:${{ inputs.gh-pat }}@github.com/.insteadOf

    - name: Setup Python packages
      shell: bash
      run: |
        python -m pip install -U pip
        python -m pip install -r crates/objs/tests/scripts/requirements.txt
        pip install -U "huggingface_hub[cli]" 