name = "Command R"
family = "command-r"
release_date = "2024-08-30"
last_updated = "2024-08-30"
attachment = false
reasoning = false
temperature = true
tool_call = true
knowledge = "2024-06-01"
open_weights = true

[limit]
context = 128_000
output = 4_000

[modalities]
input = ["text"]
output = ["text"]

[[weights]]
label = "Hugging Face"
url = "https://huggingface.co/CohereLabs/c4ai-command-r-08-2024"
