name = "GPT-5.2 Codex"
family = "gpt-codex"
release_date = "2025-12-11"
last_updated = "2025-12-11"
attachment = true
reasoning = true
reasoning_options = [{ type = "effort", values = ["low", "medium", "high", "xhigh"] }]
temperature = false
knowledge = "2025-08-31"
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 1.75
output = 14.00
cache_read = 0.175

[limit]
context = 400_000
input = 272_000
output = 128_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
