name = "North Mini Code"
family = "north"
release_date = "2026-06-09"
last_updated = "2026-06-09"
attachment = false
reasoning = true
temperature = true
structured_output = true
knowledge = "2025-09-23"
tool_call = true
open_weights = true

[limit]
context = 256_000
output = 64_000

[modalities]
input = ["text"]
output = ["text"]
