name: setup-windows
description: Sets up Windows build environment

runs:
  using: composite
  steps:
    - name: Install other build dependencies
      shell: pwsh
      if: steps.choco-cache.outputs.cache-hit != 'true'
      run: |
        choco install -y make --version=4.4.1
        choco install -y curl --version=8.11.0
