name: setup-windows
description: Sets up Windows build environment

inputs:
  GH_PAT:
    description: Github token
    required: true

runs:
  using: composite
  steps:
    - name: Install Visual Studio Build Tools
      shell: pwsh
      run: |
        # Install VS Build Tools first
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended" -y

    - name: Install other build dependencies
      shell: pwsh
      run: |
        choco install -y make cmake git python3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Enable symlinks
      shell: pwsh
      run: |
        git config --global core.symlinks true

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "windows-msvc"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Node dependencies
      shell: pwsh
      run: |
        npm install
