name: setup-windows
description: Sets up Windows build environment

inputs:
  GH_PAT:
    description: Github token
    required: true

runs:
  using: composite
  steps:
    - name: Cache Chocolatey packages
      uses: actions/cache@v4
      id: choco-cache
      with:
        path: |
          C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          C:\ProgramData\chocolatey
        key: ${{ runner.os }}-choco-${{ hashFiles('.github/actions/setup-win/action.yml') }}
        restore-keys: |
          ${{ runner.os }}-choco-

    - name: Install Visual Studio Build Tools
      shell: pwsh
      if: steps.choco-cache.outputs.cache-hit != 'true'
      run: |
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended" -y

    - name: Install other build dependencies
      shell: pwsh
      if: steps.choco-cache.outputs.cache-hit != 'true'
      run: |
        choco install -y make cmake git

    - name: Enable symlinks
      shell: pwsh
      run: |
        git config --global core.symlinks true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "windows-msvc"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/iron
