// This file is auto-generated by @hey-api/openapi-ts

export type ApiError = {
    message: string;
    type: 'api_error';
};

/**
 * Specifies who can invoke a tool.
 *
 * Values:
 * direct: The model can call this tool directly.
 * code_execution_20250825: The tool can be called from the code execution environment (v1).
 * code_execution_20260120: The tool can be called from the code execution environment (v2 with persistence).
 */
export type AllowedCaller = 'direct' | 'code_execution_20250825' | 'code_execution_20260120';

export type AuthenticationError = {
    message: string;
    type: 'authentication_error';
};

export type Base64ImageSource = {
    data: string;
    media_type: 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp';
    type: 'base64';
};

export type Base64PdfSource = {
    data: string;
    media_type: 'application/pdf';
    type: 'base64';
};

export type BashCodeExecutionToolResultErrorCode = 'invalid_tool_input' | 'unavailable' | 'too_many_requests' | 'execution_time_exceeded' | 'output_file_too_large';

export type BashTool20250124 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    input_examples?: Array<{
        [key: string]: JsonValue;
    }>;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'bash';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'bash_20250124';
};

export type BillingError = {
    message: string;
    type: 'billing_error';
};

export type CacheControlEphemeral = {
    /**
     * The time-to-live for the cache control breakpoint.
     *
     * This may be one the following values:
     * - `5m`: 5 minutes
     * - `1h`: 1 hour
     *
     * Defaults to `5m`.
     */
    ttl?: '5m' | '1h';
    type: 'ephemeral';
};

export type CacheCreation = {
    /**
     * The number of input tokens used to create the 1 hour cache entry.
     */
    ephemeral_1h_input_tokens: number;
    /**
     * The number of input tokens used to create the 5 minute cache entry.
     */
    ephemeral_5m_input_tokens: number;
};

/**
 * Indicates whether a capability is supported.
 */
export type CapabilitySupport = {
    /**
     * Whether this capability is supported by the model.
     */
    supported: boolean;
};

export type CodeExecutionToolResultErrorCode = 'invalid_tool_input' | 'unavailable' | 'too_many_requests' | 'execution_time_exceeded';

export type CodeExecutionTool20250522 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'code_execution';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'code_execution_20250522';
};

export type CodeExecutionTool20250825 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'code_execution';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'code_execution_20250825';
};

/**
 * Code execution tool with REPL state persistence (daemon mode + gVisor checkpoint).
 */
export type CodeExecutionTool20260120 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'code_execution';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'code_execution_20260120';
};

/**
 * Information about the container used in the request (for the code execution tool)
 */
export type Container = {
    /**
     * The time at which the container will expire.
     */
    expires_at: string;
    /**
     * Identifier for the container used in this request
     */
    id: string;
};

export type ContentBlockSource = {
    content: string | Array<({
        type?: 'text';
    } & RequestTextBlock) | ({
        type?: 'image';
    } & RequestImageBlock)>;
    type: 'content';
};

/**
 * Context management capability details.
 */
export type ContextManagementCapability = {
    /**
     * Whether the clear_thinking_20251015 strategy is supported.
     */
    clear_thinking_20251015: CapabilitySupport | null;
    /**
     * Whether the clear_tool_uses_20250919 strategy is supported.
     */
    clear_tool_uses_20250919: CapabilitySupport | null;
    /**
     * Whether the compact_20260112 strategy is supported.
     */
    compact_20260112: CapabilitySupport | null;
    /**
     * Whether this capability is supported by the model.
     */
    supported: boolean;
};

export type CreateMessageParams = {
    model: Model;
    /**
     * Input messages.
     *
     * Our models are trained to operate on alternating `user` and `assistant` conversational turns. When creating a new `Message`, you specify the prior conversational turns with the `messages` parameter, and the model then generates the next `Message` in the conversation. Consecutive `user` or `assistant` turns in your request will be combined into a single turn.
     *
     * Each input message must be an object with a `role` and `content`. You can specify a single `user`-role message, or you can include multiple `user` and `assistant` messages.
     *
     * If the final message uses the `assistant` role, the response content will continue immediately from the content in that message. This can be used to constrain part of the model's response.
     *
     * Example with a single `user` message:
     *
     * ```json
     * [{"role": "user", "content": "Hello, Claude"}]
     * ```
     *
     * Example with multiple conversational turns:
     *
     * ```json
     * [
     * {"role": "user", "content": "Hello there."},
     * {"role": "assistant", "content": "Hi, I'm Claude. How can I help you?"},
     * {"role": "user", "content": "Can you explain LLMs in plain English?"},
     * ]
     * ```
     *
     * Example with a partially-filled response from Claude:
     *
     * ```json
     * [
     * {"role": "user", "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C) Sun"},
     * {"role": "assistant", "content": "The best answer is ("},
     * ]
     * ```
     *
     * Each input message `content` may be either a single `string` or an array of content blocks, where each block has a specific `type`. Using a `string` for `content` is shorthand for an array of one content block of type `"text"`. The following input messages are equivalent:
     *
     * ```json
     * {"role": "user", "content": "Hello, Claude"}
     * ```
     *
     * ```json
     * {"role": "user", "content": [{"type": "text", "text": "Hello, Claude"}]}
     * ```
     *
     * See [input examples](https://docs.claude.com/en/api/messages-examples).
     *
     * Note that if you want to include a [system prompt](https://docs.claude.com/en/docs/system-prompts), you can use the top-level `system` parameter — there is no `"system"` role for input messages in the Messages API.
     *
     * There is a limit of 100,000 messages in a single request.
     */
    messages: Array<InputMessage>;
    /**
     * Top-level cache control automatically applies a cache_control marker to the last cacheable block in the request.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * Container identifier for reuse across requests.
     */
    container?: string | null;
    /**
     * Specifies the geographic region for inference processing. If not specified, the workspace's `default_inference_geo` is used.
     */
    inference_geo?: string | null;
    /**
     * The maximum number of tokens to generate before stopping.
     *
     * Note that our models may stop _before_ reaching this maximum. This parameter only specifies the absolute maximum number of tokens to generate.
     *
     * Different models have different maximum values for this parameter.  See [models](https://docs.claude.com/en/docs/models-overview) for details.
     */
    max_tokens: number;
    /**
     * An object describing metadata about the request.
     */
    metadata?: Metadata;
    /**
     * Configuration options for the model's output, such as the output format.
     */
    output_config?: OutputConfig;
    /**
     * Determines whether to use priority capacity (if available) or standard capacity for this request.
     *
     * Anthropic offers different levels of service for your API requests. See [service-tiers](https://docs.claude.com/en/api/service-tiers) for details.
     */
    service_tier?: 'auto' | 'standard_only';
    /**
     * Custom text sequences that will cause the model to stop generating.
     *
     * Our models will normally stop when they have naturally completed their turn, which will result in a response `stop_reason` of `"end_turn"`.
     *
     * If you want the model to stop generating when it encounters custom strings of text, you can use the `stop_sequences` parameter. If the model encounters one of the custom sequences, the response `stop_reason` value will be `"stop_sequence"` and the response `stop_sequence` value will contain the matched stop sequence.
     */
    stop_sequences?: Array<string>;
    /**
     * Whether to incrementally stream the response using server-sent events.
     *
     * See [streaming](https://docs.claude.com/en/api/messages-streaming) for details.
     */
    stream?: boolean;
    /**
     * System prompt.
     *
     * A system prompt is a way of providing context and instructions to Claude, such as specifying a particular goal or role. See our [guide to system prompts](https://docs.claude.com/en/docs/system-prompts).
     */
    system?: string | Array<RequestTextBlock>;
    /**
     * Amount of randomness injected into the response.
     *
     * Defaults to `1.0`. Ranges from `0.0` to `1.0`. Use `temperature` closer to `0.0` for analytical / multiple choice, and closer to `1.0` for creative and generative tasks.
     *
     * Note that even with `temperature` of `0.0`, the results will not be fully deterministic.
     * @deprecated
     */
    temperature?: number;
    thinking?: ThinkingConfigParam;
    tool_choice?: ToolChoice;
    /**
     * Definitions of tools that the model may use.
     *
     * If you include `tools` in your API request, the model may return `tool_use` content blocks that represent the model's use of those tools. You can then run those tools using the tool input generated by the model and then optionally return results back to the model using `tool_result` content blocks.
     *
     * There are two types of tools: **client tools** and **server tools**. The behavior described below applies to client tools. For [server tools](https://docs.claude.com/en/docs/agents-and-tools/tool-use/overview\#server-tools), see their individual documentation as each has its own behavior (e.g., the [web search tool](https://docs.claude.com/en/docs/agents-and-tools/tool-use/web-search-tool)).
     *
     * Each tool definition includes:
     *
     * * `name`: Name of the tool.
     * * `description`: Optional, but strongly-recommended description of the tool.
     * * `input_schema`: [JSON schema](https://json-schema.org/draft/2020-12) for the tool `input` shape that the model will produce in `tool_use` output content blocks.
     *
     * For example, if you defined `tools` as:
     *
     * ```json
     * [
     * {
     * "name": "get_stock_price",
     * "description": "Get the current stock price for a given ticker symbol.",
     * "input_schema": {
     * "type": "object",
     * "properties": {
     * "ticker": {
     * "type": "string",
     * "description": "The stock ticker symbol, e.g. AAPL for Apple Inc."
     * }
     * },
     * "required": ["ticker"]
     * }
     * }
     * ]
     * ```
     *
     * And then asked the model "What's the S&P 500 at today?", the model might produce `tool_use` content blocks in the response like this:
     *
     * ```json
     * [
     * {
     * "type": "tool_use",
     * "id": "toolu_01D7FLrfh4GYq7yT1ULFeyMV",
     * "name": "get_stock_price",
     * "input": { "ticker": "^GSPC" }
     * }
     * ]
     * ```
     *
     * You might then run your `get_stock_price` tool with `{"ticker": "^GSPC"}` as an input, and return the following back to the model in a subsequent `user` message:
     *
     * ```json
     * [
     * {
     * "type": "tool_result",
     * "tool_use_id": "toolu_01D7FLrfh4GYq7yT1ULFeyMV",
     * "content": "259.75 USD"
     * }
     * ]
     * ```
     *
     * Tools can be used for workflows that include running client-side tools and functions, or more generally whenever you want the model to produce a particular JSON structure of output.
     *
     * See our [guide](https://docs.claude.com/en/docs/tool-use) for more details.
     */
    tools?: Array<Tool | BashTool20250124 | CodeExecutionTool20250522 | CodeExecutionTool20250825 | CodeExecutionTool20260120 | MemoryTool20250818 | TextEditor20250124 | TextEditor20250429 | TextEditor20250728 | WebSearchTool20250305 | WebFetchTool20250910 | WebSearchTool20260209 | WebFetchTool20260209 | WebFetchTool20260309 | ToolSearchToolBm2520251119 | ToolSearchToolRegex20251119>;
    /**
     * Only sample from the top K options for each subsequent token.
     *
     * Used to remove "long tail" low probability responses. [Learn more technical details here](https://towardsdatascience.com/how-to-sample-from-language-models-682bceb97277).
     *
     * Recommended for advanced use cases only. You usually only need to use `temperature`.
     * @deprecated
     */
    top_k?: number;
    /**
     * Use nucleus sampling.
     *
     * In nucleus sampling, we compute the cumulative distribution over all the options for each subsequent token in decreasing probability order and cut it off once it reaches a particular probability specified by `top_p`. You should either alter `temperature` or `top_p`, but not both.
     *
     * Recommended for advanced use cases only. You usually only need to use `temperature`.
     * @deprecated
     */
    top_p?: number;
};

/**
 * Tool invocation directly from the model.
 */
export type DirectCaller = {
    type: 'direct';
};

/**
 * Effort (reasoning_effort) capability details.
 */
export type EffortCapability = {
    /**
     * Whether the model supports high effort level.
     */
    high: CapabilitySupport;
    /**
     * Whether the model supports low effort level.
     */
    low: CapabilitySupport;
    /**
     * Whether the model supports max effort level.
     */
    max: CapabilitySupport;
    /**
     * Whether the model supports medium effort level.
     */
    medium: CapabilitySupport;
    /**
     * Whether this capability is supported by the model.
     */
    supported: boolean;
};

/**
 * All possible effort levels.
 */
export type EffortLevel = 'low' | 'medium' | 'high' | 'max';

export type ErrorResponse = {
    error: ({
        type?: 'invalid_request_error';
    } & InvalidRequestError) | ({
        type?: 'authentication_error';
    } & AuthenticationError) | ({
        type?: 'billing_error';
    } & BillingError) | ({
        type?: 'permission_error';
    } & PermissionError) | ({
        type?: 'not_found_error';
    } & NotFoundError) | ({
        type?: 'rate_limit_error';
    } & RateLimitError) | ({
        type?: 'timeout_error';
    } & GatewayTimeoutError) | ({
        type?: 'api_error';
    } & ApiError) | ({
        type?: 'overloaded_error';
    } & OverloadedError);
    request_id: string | null;
    type: 'error';
};

export type GatewayTimeoutError = {
    message: string;
    type: 'timeout_error';
};

export type InputMessage = {
    content: string | Array<InputContentBlock>;
    role: 'user' | 'assistant';
};

export type InputSchema = {
    properties?: {
        [key: string]: unknown;
    } | null;
    required?: Array<string> | null;
    type: 'object';
    [key: string]: unknown | ({
        [key: string]: unknown;
    } | null) | (Array<string> | null) | 'object' | undefined;
};

export type InvalidRequestError = {
    message: string;
    type: 'invalid_request_error';
};

export type JsonOutputFormat = {
    /**
     * The JSON schema of the format
     */
    schema: {
        [key: string]: unknown;
    };
    type: 'json_schema';
};

export type JsonValue = unknown;

export type ListResponseModelInfo = {
    data: Array<ModelInfo>;
    /**
     * First ID in the `data` list. Can be used as the `before_id` for the previous page.
     */
    first_id: string | null;
    /**
     * Indicates if there are more results in the requested page direction.
     */
    has_more: boolean;
    /**
     * Last ID in the `data` list. Can be used as the `after_id` for the next page.
     */
    last_id: string | null;
};

export type MemoryTool20250818 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    input_examples?: Array<{
        [key: string]: JsonValue;
    }>;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'memory';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'memory_20250818';
};

export type Message = {
    /**
     * Unique object identifier.
     *
     * The format and length of IDs may change over time.
     */
    id: string;
    /**
     * Object type.
     *
     * For Messages, this is always `"message"`.
     */
    type: 'message';
    /**
     * Conversational role of the generated message.
     *
     * This will always be `"assistant"`.
     */
    role: 'assistant';
    /**
     * Content generated by the model.
     *
     * This is an array of content blocks, each of which has a `type` that determines its shape.
     *
     * Example:
     *
     * ```json
     * [{"type": "text", "text": "Hi, I'm Claude."}]
     * ```
     *
     * If the request input `messages` ended with an `assistant` turn, then the response `content` will continue directly from that last turn. You can use this to constrain the model's output.
     *
     * For example, if the input `messages` were:
     * ```json
     * [
     * {"role": "user", "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C) Sun"},
     * {"role": "assistant", "content": "The best answer is ("}
     * ]
     * ```
     *
     * Then the response `content` might be:
     *
     * ```json
     * [{"type": "text", "text": "B)"}]
     * ```
     */
    content: Array<ContentBlock>;
    model: Model;
    /**
     * The reason that we stopped.
     *
     * This may be one the following values:
     * * `"end_turn"`: the model reached a natural stopping point
     * * `"max_tokens"`: we exceeded the requested `max_tokens` or the model's maximum
     * * `"stop_sequence"`: one of your provided custom `stop_sequences` was generated
     * * `"tool_use"`: the model invoked one or more tools
     * * `"pause_turn"`: we paused a long-running turn. You may provide the response back as-is in a subsequent request to let the model continue.
     * * `"refusal"`: when streaming classifiers intervene to handle potential policy violations
     *
     * In non-streaming mode this value is always non-null. In streaming mode, it is null in the `message_start` event and non-null otherwise.
     */
    stop_reason: StopReason | null;
    /**
     * Which custom stop sequence was generated, if any.
     *
     * This value will be a non-null string if one of your custom stop sequences was generated.
     */
    stop_sequence: string | null;
    /**
     * Structured information about why model output stopped.
     *
     * This is `null` when the `stop_reason` has no additional detail to report.
     */
    stop_details: RefusalStopDetails | null;
    /**
     * Billing and rate-limit usage.
     *
     * Anthropic's API bills and rate-limits by token counts, as tokens represent the underlying cost to our systems.
     *
     * Under the hood, the API transforms requests into a format suitable for the model. The model's output then goes through a parsing stage before becoming an API response. As a result, the token counts in `usage` will not match one-to-one with the exact visible content of an API request or response.
     *
     * For example, `output_tokens` will be non-zero, even for an empty string response from Claude.
     *
     * Total input tokens in a request is the summation of `input_tokens`, `cache_creation_input_tokens`, and `cache_read_input_tokens`.
     */
    usage: Usage;
    /**
     * Information about the container used in this request.
     *
     * This will be non-null if a container tool (e.g. code execution) was used.
     */
    container: Container | null;
};

export type Metadata = {
    /**
     * An external identifier for the user who is associated with the request.
     *
     * This should be a uuid, hash value, or other opaque identifier. Anthropic may use this id to help detect abuse. Do not include any identifying information such as name, email address, or phone number.
     */
    user_id?: string | null;
};

/**
 * Model capability information.
 */
export type ModelCapabilities = {
    /**
     * Whether the model supports the Batch API.
     */
    batch: CapabilitySupport;
    /**
     * Whether the model supports citation generation.
     */
    citations: CapabilitySupport;
    /**
     * Whether the model supports code execution tools.
     */
    code_execution: CapabilitySupport;
    /**
     * Context management support and available strategies.
     */
    context_management: ContextManagementCapability;
    /**
     * Effort (reasoning_effort) support and available levels.
     */
    effort: EffortCapability;
    /**
     * Whether the model accepts image content blocks.
     */
    image_input: CapabilitySupport;
    /**
     * Whether the model accepts PDF content blocks.
     */
    pdf_input: CapabilitySupport;
    /**
     * Whether the model supports structured output / JSON mode / strict tool schemas.
     */
    structured_outputs: CapabilitySupport;
    /**
     * Thinking capability and supported type configurations.
     */
    thinking: ThinkingCapability;
};

export type ModelInfo = {
    /**
     * Object mapping capability names to their support details. Keys are always present for all known capabilities.
     */
    capabilities: ModelCapabilities | null;
    /**
     * RFC 3339 datetime string representing the time at which the model was released. May be set to an epoch value if the release date is unknown.
     */
    created_at: string;
    /**
     * A human-readable name for the model.
     */
    display_name: string;
    /**
     * Unique model identifier.
     */
    id: string;
    /**
     * Maximum input context window size in tokens for this model.
     */
    max_input_tokens: number | null;
    /**
     * Maximum value for the `max_tokens` parameter when using this model.
     */
    max_tokens: number | null;
    /**
     * Object type.
     *
     * For Models, this is always `"model"`.
     */
    type: 'model';
};

export type NotFoundError = {
    message: string;
    type: 'not_found_error';
};

export type OutputConfig = {
    /**
     * How much effort the model should put into its response. Higher effort levels may result in more thorough analysis but take longer.
     *
     * Valid values are `low`, `medium`, `high`, or `max`.
     */
    effort?: EffortLevel | null;
    /**
     * A schema to specify Claude's output format in responses. See [structured outputs](https://platform.claude.com/docs/en/build-with-claude/structured-outputs)
     */
    format?: JsonOutputFormat | null;
};

export type OverloadedError = {
    message: string;
    type: 'overloaded_error';
};

export type PermissionError = {
    message: string;
    type: 'permission_error';
};

export type PlainTextSource = {
    data: string;
    media_type: 'text/plain';
    type: 'text';
};

export type RateLimitError = {
    message: string;
    type: 'rate_limit_error';
};

/**
 * Structured information about a refusal.
 */
export type RefusalStopDetails = {
    /**
     * The policy category that triggered the refusal.
     *
     * `null` when the refusal doesn't map to a named category.
     */
    category: ('cyber' | 'bio') | null;
    /**
     * Human-readable explanation of the refusal.
     *
     * This text is not guaranteed to be stable. `null` when no explanation is available for the category.
     */
    explanation: string | null;
    type: 'refusal';
};

export type RequestBashCodeExecutionOutputBlock = {
    file_id: string;
    type: 'bash_code_execution_output';
};

export type RequestBashCodeExecutionResultBlock = {
    content: Array<RequestBashCodeExecutionOutputBlock>;
    return_code: number;
    stderr: string;
    stdout: string;
    type: 'bash_code_execution_result';
};

export type RequestBashCodeExecutionToolResultBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    content: RequestBashCodeExecutionToolResultError | RequestBashCodeExecutionResultBlock;
    tool_use_id: string;
    type: 'bash_code_execution_tool_result';
};

export type RequestBashCodeExecutionToolResultError = {
    error_code: BashCodeExecutionToolResultErrorCode;
    type: 'bash_code_execution_tool_result_error';
};

export type RequestCharLocationCitation = {
    cited_text: string;
    document_index: number;
    document_title: string | null;
    end_char_index: number;
    start_char_index: number;
    type: 'char_location';
};

export type RequestCitationsConfig = {
    enabled?: boolean;
};

export type RequestCodeExecutionOutputBlock = {
    file_id: string;
    type: 'code_execution_output';
};

export type RequestCodeExecutionResultBlock = {
    content: Array<RequestCodeExecutionOutputBlock>;
    return_code: number;
    stderr: string;
    stdout: string;
    type: 'code_execution_result';
};

export type RequestCodeExecutionToolResultBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    content: RequestCodeExecutionToolResultError | RequestCodeExecutionResultBlock | RequestEncryptedCodeExecutionResultBlock;
    tool_use_id: string;
    type: 'code_execution_tool_result';
};

export type RequestCodeExecutionToolResultError = {
    error_code: CodeExecutionToolResultErrorCode;
    type: 'code_execution_tool_result_error';
};

/**
 * A content block that represents a file to be uploaded to the container
 * Files uploaded via this block will be available in the container's input directory.
 */
export type RequestContainerUploadBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    file_id: string;
    type: 'container_upload';
};

export type RequestContentBlockLocationCitation = {
    cited_text: string;
    document_index: number;
    document_title: string | null;
    end_block_index: number;
    start_block_index: number;
    type: 'content_block_location';
};

export type RequestDocumentBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    citations?: RequestCitationsConfig | null;
    context?: string | null;
    source: ({
        type?: 'base64';
    } & Base64PdfSource) | ({
        type?: 'text';
    } & PlainTextSource) | ({
        type?: 'content';
    } & ContentBlockSource) | ({
        type?: 'url';
    } & UrlpdfSource);
    title?: string | null;
    type: 'document';
};

/**
 * Code execution result with encrypted stdout for PFC + web_search results.
 */
export type RequestEncryptedCodeExecutionResultBlock = {
    content: Array<RequestCodeExecutionOutputBlock>;
    encrypted_stdout: string;
    return_code: number;
    stderr: string;
    type: 'encrypted_code_execution_result';
};

export type RequestImageBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    source: ({
        type?: 'base64';
    } & Base64ImageSource) | ({
        type?: 'url';
    } & UrlImageSource);
    type: 'image';
};

export type RequestPageLocationCitation = {
    cited_text: string;
    document_index: number;
    document_title: string | null;
    end_page_number: number;
    start_page_number: number;
    type: 'page_location';
};

export type RequestRedactedThinkingBlock = {
    data: string;
    type: 'redacted_thinking';
};

export type RequestSearchResultBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    citations?: RequestCitationsConfig;
    content: Array<RequestTextBlock>;
    source: string;
    title: string;
    type: 'search_result';
};

export type RequestSearchResultLocationCitation = {
    cited_text: string;
    end_block_index: number;
    search_result_index: number;
    source: string;
    start_block_index: number;
    title: string | null;
    type: 'search_result_location';
};

export type RequestServerToolUseBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    caller?: ({
        type?: 'direct';
    } & DirectCaller) | ({
        type?: 'code_execution_20250825';
    } & ServerToolCaller) | ({
        type?: 'code_execution_20260120';
    } & ServerToolCaller20260120);
    id: string;
    input: {
        [key: string]: unknown;
    };
    name: 'web_search' | 'web_fetch' | 'code_execution' | 'bash_code_execution' | 'text_editor_code_execution' | 'tool_search_tool_regex' | 'tool_search_tool_bm25';
    type: 'server_tool_use';
};

export type RequestTextBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    citations?: Array<({
        type?: 'char_location';
    } & RequestCharLocationCitation) | ({
        type?: 'page_location';
    } & RequestPageLocationCitation) | ({
        type?: 'content_block_location';
    } & RequestContentBlockLocationCitation) | ({
        type?: 'web_search_result_location';
    } & RequestWebSearchResultLocationCitation) | ({
        type?: 'search_result_location';
    } & RequestSearchResultLocationCitation)> | null;
    text: string;
    type: 'text';
};

export type RequestTextEditorCodeExecutionCreateResultBlock = {
    is_file_update: boolean;
    type: 'text_editor_code_execution_create_result';
};

export type RequestTextEditorCodeExecutionStrReplaceResultBlock = {
    lines?: Array<string> | null;
    new_lines?: number | null;
    new_start?: number | null;
    old_lines?: number | null;
    old_start?: number | null;
    type: 'text_editor_code_execution_str_replace_result';
};

export type RequestTextEditorCodeExecutionToolResultBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    content: RequestTextEditorCodeExecutionToolResultError | RequestTextEditorCodeExecutionViewResultBlock | RequestTextEditorCodeExecutionCreateResultBlock | RequestTextEditorCodeExecutionStrReplaceResultBlock;
    tool_use_id: string;
    type: 'text_editor_code_execution_tool_result';
};

export type RequestTextEditorCodeExecutionToolResultError = {
    error_code: TextEditorCodeExecutionToolResultErrorCode;
    error_message?: string | null;
    type: 'text_editor_code_execution_tool_result_error';
};

export type RequestTextEditorCodeExecutionViewResultBlock = {
    content: string;
    file_type: 'text' | 'image' | 'pdf';
    num_lines?: number | null;
    start_line?: number | null;
    total_lines?: number | null;
    type: 'text_editor_code_execution_view_result';
};

export type RequestThinkingBlock = {
    signature: string;
    thinking: string;
    type: 'thinking';
};

/**
 * Tool reference block that can be included in tool_result content.
 */
export type RequestToolReferenceBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    tool_name: string;
    type: 'tool_reference';
};

export type RequestToolResultBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    content?: string | Array<({
        type?: 'text';
    } & RequestTextBlock) | ({
        type?: 'image';
    } & RequestImageBlock) | ({
        type?: 'search_result';
    } & RequestSearchResultBlock) | ({
        type?: 'document';
    } & RequestDocumentBlock) | ({
        type?: 'tool_reference';
    } & RequestToolReferenceBlock)>;
    is_error?: boolean;
    tool_use_id: string;
    type: 'tool_result';
};

export type RequestToolSearchToolResultBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    content: RequestToolSearchToolResultError | RequestToolSearchToolSearchResultBlock;
    tool_use_id: string;
    type: 'tool_search_tool_result';
};

export type RequestToolSearchToolResultError = {
    error_code: ToolSearchToolResultErrorCode;
    type: 'tool_search_tool_result_error';
};

export type RequestToolSearchToolSearchResultBlock = {
    tool_references: Array<RequestToolReferenceBlock>;
    type: 'tool_search_tool_search_result';
};

export type RequestToolUseBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    caller?: ({
        type?: 'direct';
    } & DirectCaller) | ({
        type?: 'code_execution_20250825';
    } & ServerToolCaller) | ({
        type?: 'code_execution_20260120';
    } & ServerToolCaller20260120);
    id: string;
    input: {
        [key: string]: unknown;
    };
    name: string;
    type: 'tool_use';
};

export type RequestWebFetchResultBlock = {
    content: RequestDocumentBlock;
    /**
     * ISO 8601 timestamp when the content was retrieved
     */
    retrieved_at?: string | null;
    type: 'web_fetch_result';
    /**
     * Fetched content URL
     */
    url: string;
};

export type RequestWebFetchToolResultBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    caller?: ({
        type?: 'direct';
    } & DirectCaller) | ({
        type?: 'code_execution_20250825';
    } & ServerToolCaller) | ({
        type?: 'code_execution_20260120';
    } & ServerToolCaller20260120);
    content: RequestWebFetchToolResultError | RequestWebFetchResultBlock;
    tool_use_id: string;
    type: 'web_fetch_tool_result';
};

export type RequestWebFetchToolResultError = {
    error_code: WebFetchToolResultErrorCode;
    type: 'web_fetch_tool_result_error';
};

export type RequestWebSearchResultBlock = {
    encrypted_content: string;
    page_age?: string | null;
    title: string;
    type: 'web_search_result';
    url: string;
};

export type RequestWebSearchResultLocationCitation = {
    cited_text: string;
    encrypted_index: string;
    title: string | null;
    type: 'web_search_result_location';
    url: string;
};

export type RequestWebSearchToolResultBlock = {
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    caller?: ({
        type?: 'direct';
    } & DirectCaller) | ({
        type?: 'code_execution_20250825';
    } & ServerToolCaller) | ({
        type?: 'code_execution_20260120';
    } & ServerToolCaller20260120);
    content: Array<RequestWebSearchResultBlock> | RequestWebSearchToolResultError;
    tool_use_id: string;
    type: 'web_search_tool_result';
};

export type RequestWebSearchToolResultError = {
    error_code: WebSearchToolResultErrorCode;
    type: 'web_search_tool_result_error';
};

export type ResponseBashCodeExecutionOutputBlock = {
    file_id: string;
    type: 'bash_code_execution_output';
};

export type ResponseBashCodeExecutionResultBlock = {
    content: Array<ResponseBashCodeExecutionOutputBlock>;
    return_code: number;
    stderr: string;
    stdout: string;
    type: 'bash_code_execution_result';
};

export type ResponseBashCodeExecutionToolResultBlock = {
    content: ResponseBashCodeExecutionToolResultError | ResponseBashCodeExecutionResultBlock;
    tool_use_id: string;
    type: 'bash_code_execution_tool_result';
};

export type ResponseBashCodeExecutionToolResultError = {
    error_code: BashCodeExecutionToolResultErrorCode;
    type: 'bash_code_execution_tool_result_error';
};

export type ResponseCharLocationCitation = {
    cited_text: string;
    document_index: number;
    document_title: string | null;
    end_char_index: number;
    file_id: string | null;
    start_char_index: number;
    type: 'char_location';
};

export type ResponseCitationsConfig = {
    enabled: boolean;
};

export type ResponseCodeExecutionOutputBlock = {
    file_id: string;
    type: 'code_execution_output';
};

export type ResponseCodeExecutionResultBlock = {
    content: Array<ResponseCodeExecutionOutputBlock>;
    return_code: number;
    stderr: string;
    stdout: string;
    type: 'code_execution_result';
};

export type ResponseCodeExecutionToolResultBlock = {
    content: ResponseCodeExecutionToolResultError | ResponseCodeExecutionResultBlock | ResponseEncryptedCodeExecutionResultBlock;
    tool_use_id: string;
    type: 'code_execution_tool_result';
};

export type ResponseCodeExecutionToolResultError = {
    error_code: CodeExecutionToolResultErrorCode;
    type: 'code_execution_tool_result_error';
};

/**
 * Response model for a file uploaded to the container.
 */
export type ResponseContainerUploadBlock = {
    file_id: string;
    type: 'container_upload';
};

export type ResponseContentBlockLocationCitation = {
    cited_text: string;
    document_index: number;
    document_title: string | null;
    end_block_index: number;
    file_id: string | null;
    start_block_index: number;
    type: 'content_block_location';
};

export type ResponseDocumentBlock = {
    /**
     * Citation configuration for the document
     */
    citations: ResponseCitationsConfig | null;
    source: ({
        type?: 'base64';
    } & Base64PdfSource) | ({
        type?: 'text';
    } & PlainTextSource);
    /**
     * The title of the document
     */
    title: string | null;
    type: 'document';
};

/**
 * Code execution result with encrypted stdout for PFC + web_search results.
 */
export type ResponseEncryptedCodeExecutionResultBlock = {
    content: Array<ResponseCodeExecutionOutputBlock>;
    encrypted_stdout: string;
    return_code: number;
    stderr: string;
    type: 'encrypted_code_execution_result';
};

export type ResponsePageLocationCitation = {
    cited_text: string;
    document_index: number;
    document_title: string | null;
    end_page_number: number;
    file_id: string | null;
    start_page_number: number;
    type: 'page_location';
};

export type ResponseRedactedThinkingBlock = {
    data: string;
    type: 'redacted_thinking';
};

export type ResponseSearchResultLocationCitation = {
    cited_text: string;
    end_block_index: number;
    search_result_index: number;
    source: string;
    start_block_index: number;
    title: string | null;
    type: 'search_result_location';
};

export type ResponseServerToolUseBlock = {
    caller: ({
        type?: 'direct';
    } & DirectCaller) | ({
        type?: 'code_execution_20250825';
    } & ServerToolCaller) | ({
        type?: 'code_execution_20260120';
    } & ServerToolCaller20260120);
    id: string;
    input: {
        [key: string]: unknown;
    };
    name: 'web_search' | 'web_fetch' | 'code_execution' | 'bash_code_execution' | 'text_editor_code_execution' | 'tool_search_tool_regex' | 'tool_search_tool_bm25';
    type: 'server_tool_use';
};

export type ResponseTextBlock = {
    /**
     * Citations supporting the text block.
     *
     * The type of citation returned will depend on the type of document being cited. Citing a PDF results in `page_location`, plain text results in `char_location`, and content document results in `content_block_location`.
     */
    citations: Array<({
        type?: 'char_location';
    } & ResponseCharLocationCitation) | ({
        type?: 'page_location';
    } & ResponsePageLocationCitation) | ({
        type?: 'content_block_location';
    } & ResponseContentBlockLocationCitation) | ({
        type?: 'web_search_result_location';
    } & ResponseWebSearchResultLocationCitation) | ({
        type?: 'search_result_location';
    } & ResponseSearchResultLocationCitation)> | null;
    text: string;
    type: 'text';
};

export type ResponseTextEditorCodeExecutionCreateResultBlock = {
    is_file_update: boolean;
    type: 'text_editor_code_execution_create_result';
};

export type ResponseTextEditorCodeExecutionStrReplaceResultBlock = {
    lines: Array<string> | null;
    new_lines: number | null;
    new_start: number | null;
    old_lines: number | null;
    old_start: number | null;
    type: 'text_editor_code_execution_str_replace_result';
};

export type ResponseTextEditorCodeExecutionToolResultBlock = {
    content: ResponseTextEditorCodeExecutionToolResultError | ResponseTextEditorCodeExecutionViewResultBlock | ResponseTextEditorCodeExecutionCreateResultBlock | ResponseTextEditorCodeExecutionStrReplaceResultBlock;
    tool_use_id: string;
    type: 'text_editor_code_execution_tool_result';
};

export type ResponseTextEditorCodeExecutionToolResultError = {
    error_code: TextEditorCodeExecutionToolResultErrorCode;
    error_message: string | null;
    type: 'text_editor_code_execution_tool_result_error';
};

export type ResponseTextEditorCodeExecutionViewResultBlock = {
    content: string;
    file_type: 'text' | 'image' | 'pdf';
    num_lines: number | null;
    start_line: number | null;
    total_lines: number | null;
    type: 'text_editor_code_execution_view_result';
};

export type ResponseThinkingBlock = {
    signature: string;
    thinking: string;
    type: 'thinking';
};

export type ResponseToolReferenceBlock = {
    tool_name: string;
    type: 'tool_reference';
};

export type ResponseToolSearchToolResultBlock = {
    content: ResponseToolSearchToolResultError | ResponseToolSearchToolSearchResultBlock;
    tool_use_id: string;
    type: 'tool_search_tool_result';
};

export type ResponseToolSearchToolResultError = {
    error_code: ToolSearchToolResultErrorCode;
    error_message: string | null;
    type: 'tool_search_tool_result_error';
};

export type ResponseToolSearchToolSearchResultBlock = {
    tool_references: Array<ResponseToolReferenceBlock>;
    type: 'tool_search_tool_search_result';
};

export type ResponseToolUseBlock = {
    caller: ({
        type?: 'direct';
    } & DirectCaller) | ({
        type?: 'code_execution_20250825';
    } & ServerToolCaller) | ({
        type?: 'code_execution_20260120';
    } & ServerToolCaller20260120);
    id: string;
    input: {
        [key: string]: unknown;
    };
    name: string;
    type: 'tool_use';
};

export type ResponseWebFetchResultBlock = {
    content: ResponseDocumentBlock;
    /**
     * ISO 8601 timestamp when the content was retrieved
     */
    retrieved_at: string | null;
    type: 'web_fetch_result';
    /**
     * Fetched content URL
     */
    url: string;
};

export type ResponseWebFetchToolResultBlock = {
    caller: ({
        type?: 'direct';
    } & DirectCaller) | ({
        type?: 'code_execution_20250825';
    } & ServerToolCaller) | ({
        type?: 'code_execution_20260120';
    } & ServerToolCaller20260120);
    content: ResponseWebFetchToolResultError | ResponseWebFetchResultBlock;
    tool_use_id: string;
    type: 'web_fetch_tool_result';
};

export type ResponseWebFetchToolResultError = {
    error_code: WebFetchToolResultErrorCode;
    type: 'web_fetch_tool_result_error';
};

export type ResponseWebSearchResultBlock = {
    encrypted_content: string;
    page_age: string | null;
    title: string;
    type: 'web_search_result';
    url: string;
};

export type ResponseWebSearchResultLocationCitation = {
    cited_text: string;
    encrypted_index: string;
    title: string | null;
    type: 'web_search_result_location';
    url: string;
};

export type ResponseWebSearchToolResultBlock = {
    caller: ({
        type?: 'direct';
    } & DirectCaller) | ({
        type?: 'code_execution_20250825';
    } & ServerToolCaller) | ({
        type?: 'code_execution_20260120';
    } & ServerToolCaller20260120);
    content: ResponseWebSearchToolResultError | Array<ResponseWebSearchResultBlock>;
    tool_use_id: string;
    type: 'web_search_tool_result';
};

export type ResponseWebSearchToolResultError = {
    error_code: WebSearchToolResultErrorCode;
    type: 'web_search_tool_result_error';
};

/**
 * Tool invocation generated by a server-side tool.
 */
export type ServerToolCaller = {
    tool_id: string;
    type: 'code_execution_20250825';
};

export type ServerToolCaller20260120 = {
    tool_id: string;
    type: 'code_execution_20260120';
};

export type ServerToolUsage = {
    /**
     * The number of web fetch tool requests.
     */
    web_fetch_requests: number;
    /**
     * The number of web search tool requests.
     */
    web_search_requests: number;
};

export type TextEditorCodeExecutionToolResultErrorCode = 'invalid_tool_input' | 'unavailable' | 'too_many_requests' | 'execution_time_exceeded' | 'file_not_found';

export type TextEditor20250124 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    input_examples?: Array<{
        [key: string]: JsonValue;
    }>;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'str_replace_editor';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'text_editor_20250124';
};

export type TextEditor20250429 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    input_examples?: Array<{
        [key: string]: JsonValue;
    }>;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'str_replace_based_edit_tool';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'text_editor_20250429';
};

export type TextEditor20250728 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    input_examples?: Array<{
        [key: string]: JsonValue;
    }>;
    /**
     * Maximum number of characters to display when viewing a file. If not specified, defaults to displaying the full file.
     */
    max_characters?: number | null;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'str_replace_based_edit_tool';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'text_editor_20250728';
};

/**
 * Thinking capability details.
 */
export type ThinkingCapability = {
    /**
     * Whether this capability is supported by the model.
     */
    supported: boolean;
    types: ThinkingTypes;
};

export type ThinkingConfigAdaptive = {
    /**
     * Controls how thinking content appears in the response. When set to `summarized`, thinking is returned normally. When set to `omitted`, thinking content is redacted but a signature is returned for multi-turn continuity. Defaults to `summarized`.
     */
    display?: ThinkingDisplayMode | null;
    type: 'adaptive';
};

export type ThinkingConfigDisabled = {
    type: 'disabled';
};

export type ThinkingConfigEnabled = {
    /**
     * Determines how many tokens Claude can use for its internal reasoning process. Larger budgets can enable more thorough analysis for complex problems, improving response quality.
     *
     * Must be ≥1024 and less than `max_tokens`.
     *
     * See [extended thinking](https://docs.claude.com/en/docs/build-with-claude/extended-thinking) for details.
     */
    budget_tokens: number;
    /**
     * Controls how thinking content appears in the response. When set to `summarized`, thinking is returned normally. When set to `omitted`, thinking content is redacted but a signature is returned for multi-turn continuity. Defaults to `summarized`.
     */
    display?: ThinkingDisplayMode | null;
    type: 'enabled';
};

export type ThinkingDisplayMode = 'summarized' | 'omitted';

/**
 * Supported thinking type configurations.
 */
export type ThinkingTypes = {
    /**
     * Whether the model supports thinking with type 'adaptive' (auto).
     */
    adaptive: CapabilitySupport;
    /**
     * Whether the model supports thinking with type 'enabled'.
     */
    enabled: CapabilitySupport;
};

export type Tool = {
    type?: null | 'custom';
    /**
     * Description of what this tool does.
     *
     * Tool descriptions should be as detailed as possible. The more information that the model has about what the tool is and how to use it, the better it will perform. You can use natural language descriptions to reinforce important aspects of the tool input JSON schema.
     */
    description?: string;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: string;
    /**
     * [JSON schema](https://json-schema.org/draft/2020-12) for this tool's input.
     *
     * This defines the shape of the `input` that your tool accepts and that the model will produce.
     */
    input_schema: InputSchema;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    /**
     * Enable eager input streaming for this tool. When true, tool input parameters will be streamed incrementally as they are generated, and types will be inferred on-the-fly rather than buffering the full JSON output. When false, streaming is disabled for this tool even if the fine-grained-tool-streaming beta is active. When null (default), uses the default behavior based on beta headers.
     */
    eager_input_streaming?: boolean | null;
    allowed_callers?: Array<AllowedCaller>;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    input_examples?: Array<{
        [key: string]: JsonValue;
    }>;
};

/**
 * The model will use any available tools.
 */
export type ToolChoiceAny = {
    /**
     * Whether to disable parallel tool use.
     *
     * Defaults to `false`. If set to `true`, the model will output exactly one tool use.
     */
    disable_parallel_tool_use?: boolean;
    type: 'any';
};

/**
 * The model will automatically decide whether to use tools.
 */
export type ToolChoiceAuto = {
    /**
     * Whether to disable parallel tool use.
     *
     * Defaults to `false`. If set to `true`, the model will output at most one tool use.
     */
    disable_parallel_tool_use?: boolean;
    type: 'auto';
};

/**
 * The model will not be allowed to use tools.
 */
export type ToolChoiceNone = {
    type: 'none';
};

/**
 * The model will use the specified tool with `tool_choice.name`.
 */
export type ToolChoiceTool = {
    /**
     * Whether to disable parallel tool use.
     *
     * Defaults to `false`. If set to `true`, the model will output exactly one tool use.
     */
    disable_parallel_tool_use?: boolean;
    /**
     * The name of the tool to use.
     */
    name: string;
    type: 'tool';
};

export type ToolSearchToolBm2520251119 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'tool_search_tool_bm25';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'tool_search_tool_bm25_20251119' | 'tool_search_tool_bm25';
};

export type ToolSearchToolRegex20251119 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'tool_search_tool_regex';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'tool_search_tool_regex_20251119' | 'tool_search_tool_regex';
};

export type ToolSearchToolResultErrorCode = 'invalid_tool_input' | 'unavailable' | 'too_many_requests' | 'execution_time_exceeded';

export type UrlImageSource = {
    type: 'url';
    url: string;
};

export type UrlpdfSource = {
    type: 'url';
    url: string;
};

export type Usage = {
    /**
     * Breakdown of cached tokens by TTL
     */
    cache_creation: CacheCreation | null;
    /**
     * The number of input tokens used to create the cache entry.
     */
    cache_creation_input_tokens: number | null;
    /**
     * The number of input tokens read from the cache.
     */
    cache_read_input_tokens: number | null;
    /**
     * The geographic region where inference was performed for this request.
     */
    inference_geo: string | null;
    /**
     * The number of input tokens which were used.
     */
    input_tokens: number;
    /**
     * The number of output tokens which were used.
     */
    output_tokens: number;
    /**
     * The number of server tool requests.
     */
    server_tool_use: ServerToolUsage | null;
    /**
     * If the request used the priority, standard, or batch tier.
     */
    service_tier: ('standard' | 'priority' | 'batch') | null;
};

export type UserLocation = {
    /**
     * The city of the user.
     */
    city?: string | null;
    /**
     * The two letter [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the user.
     */
    country?: string | null;
    /**
     * The region of the user.
     */
    region?: string | null;
    /**
     * The [IANA timezone](https://nodatime.org/TimeZones) of the user.
     */
    timezone?: string | null;
    type: 'approximate';
};

export type WebFetchToolResultErrorCode = 'invalid_tool_input' | 'url_too_long' | 'url_not_allowed' | 'url_not_accessible' | 'unsupported_content_type' | 'too_many_requests' | 'max_uses_exceeded' | 'unavailable';

export type WebFetchTool20250910 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * List of domains to allow fetching from
     */
    allowed_domains?: Array<string> | null;
    /**
     * List of domains to block fetching from
     */
    blocked_domains?: Array<string> | null;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * Citations configuration for fetched documents. Citations are disabled by default.
     */
    citations?: RequestCitationsConfig | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    /**
     * Maximum number of tokens used by including web page text content in the context. The limit is approximate and does not apply to binary content such as PDFs.
     */
    max_content_tokens?: number | null;
    /**
     * Maximum number of times the tool can be used in the API request.
     */
    max_uses?: number | null;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'web_fetch';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'web_fetch_20250910';
};

export type WebFetchTool20260209 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * List of domains to allow fetching from
     */
    allowed_domains?: Array<string> | null;
    /**
     * List of domains to block fetching from
     */
    blocked_domains?: Array<string> | null;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * Citations configuration for fetched documents. Citations are disabled by default.
     */
    citations?: RequestCitationsConfig | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    /**
     * Maximum number of tokens used by including web page text content in the context. The limit is approximate and does not apply to binary content such as PDFs.
     */
    max_content_tokens?: number | null;
    /**
     * Maximum number of times the tool can be used in the API request.
     */
    max_uses?: number | null;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'web_fetch';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'web_fetch_20260209';
};

/**
 * Web fetch tool with use_cache parameter for bypassing cached content.
 */
export type WebFetchTool20260309 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * List of domains to allow fetching from
     */
    allowed_domains?: Array<string> | null;
    /**
     * List of domains to block fetching from
     */
    blocked_domains?: Array<string> | null;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * Citations configuration for fetched documents. Citations are disabled by default.
     */
    citations?: RequestCitationsConfig | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    /**
     * Maximum number of tokens used by including web page text content in the context. The limit is approximate and does not apply to binary content such as PDFs.
     */
    max_content_tokens?: number | null;
    /**
     * Maximum number of times the tool can be used in the API request.
     */
    max_uses?: number | null;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'web_fetch';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'web_fetch_20260309';
    /**
     * Whether to use cached content. Set to false to bypass the cache and fetch fresh content. Only set to false when the user explicitly requests fresh content or when fetching rapidly-changing sources.
     */
    use_cache?: boolean;
};

export type WebSearchToolResultErrorCode = 'invalid_tool_input' | 'unavailable' | 'max_uses_exceeded' | 'too_many_requests' | 'query_too_long' | 'request_too_large';

export type WebSearchTool20250305 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * If provided, only these domains will be included in results. Cannot be used alongside `blocked_domains`.
     */
    allowed_domains?: Array<string> | null;
    /**
     * If provided, these domains will never appear in results. Cannot be used alongside `allowed_domains`.
     */
    blocked_domains?: Array<string> | null;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    /**
     * Maximum number of times the tool can be used in the API request.
     */
    max_uses?: number | null;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'web_search';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'web_search_20250305';
    /**
     * Parameters for the user's location. Used to provide more relevant search results.
     */
    user_location?: UserLocation | null;
};

export type WebSearchTool20260209 = {
    allowed_callers?: Array<AllowedCaller>;
    /**
     * If provided, only these domains will be included in results. Cannot be used alongside `blocked_domains`.
     */
    allowed_domains?: Array<string> | null;
    /**
     * If provided, these domains will never appear in results. Cannot be used alongside `allowed_domains`.
     */
    blocked_domains?: Array<string> | null;
    /**
     * Create a cache control breakpoint at this content block.
     */
    cache_control?: ({
        type?: 'ephemeral';
    } & CacheControlEphemeral) | null;
    /**
     * If true, tool will not be included in initial system prompt. Only loaded when returned via tool_reference from tool search.
     */
    defer_loading?: boolean;
    /**
     * Maximum number of times the tool can be used in the API request.
     */
    max_uses?: number | null;
    /**
     * Name of the tool.
     *
     * This is how the tool will be called by the model and in `tool_use` blocks.
     */
    name: 'web_search';
    /**
     * When true, guarantees schema validation on tool names and inputs
     */
    strict?: boolean;
    type: 'web_search_20260209';
    /**
     * Parameters for the user's location. Used to provide more relevant search results.
     */
    user_location?: UserLocation | null;
};

export type AnthropicBeta = string | ('message-batches-2024-09-24' | 'prompt-caching-2024-07-31' | 'computer-use-2024-10-22' | 'computer-use-2025-01-24' | 'pdfs-2024-09-25' | 'token-counting-2024-11-01' | 'token-efficient-tools-2025-02-19' | 'output-128k-2025-02-19' | 'files-api-2025-04-14' | 'mcp-client-2025-04-04' | 'mcp-client-2025-11-20' | 'dev-full-thinking-2025-05-14' | 'interleaved-thinking-2025-05-14' | 'code-execution-2025-05-22' | 'extended-cache-ttl-2025-04-11' | 'context-1m-2025-08-07' | 'context-management-2025-06-27' | 'model-context-window-exceeded-2025-08-26' | 'skills-2025-10-02' | 'fast-mode-2026-02-01' | 'output-300k-2026-03-24' | 'advisor-tool-2026-03-01');

/**
 * Configuration for enabling Claude's extended thinking.
 *
 * When enabled, responses include `thinking` content blocks showing Claude's thinking process before the final answer. Requires a minimum budget of 1,024 tokens and counts towards your `max_tokens` limit.
 *
 * See [extended thinking](https://docs.claude.com/en/docs/build-with-claude/extended-thinking) for details.
 */
export type ThinkingConfigParam = ({
    type?: 'enabled';
} & ThinkingConfigEnabled) | ({
    type?: 'disabled';
} & ThinkingConfigDisabled) | ({
    type?: 'adaptive';
} & ThinkingConfigAdaptive);

/**
 * How the model should use the provided tools. The model can use a specific tool, any available tool, decide by itself, or not use tools at all.
 */
export type ToolChoice = ({
    type?: 'auto';
} & ToolChoiceAuto) | ({
    type?: 'any';
} & ToolChoiceAny) | ({
    type?: 'tool';
} & ToolChoiceTool) | ({
    type?: 'none';
} & ToolChoiceNone);

export type ContentBlock = ({
    type?: 'text';
} & ResponseTextBlock) | ({
    type?: 'thinking';
} & ResponseThinkingBlock) | ({
    type?: 'redacted_thinking';
} & ResponseRedactedThinkingBlock) | ({
    type?: 'tool_use';
} & ResponseToolUseBlock) | ({
    type?: 'server_tool_use';
} & ResponseServerToolUseBlock) | ({
    type?: 'web_search_tool_result';
} & ResponseWebSearchToolResultBlock) | ({
    type?: 'web_fetch_tool_result';
} & ResponseWebFetchToolResultBlock) | ({
    type?: 'code_execution_tool_result';
} & ResponseCodeExecutionToolResultBlock) | ({
    type?: 'bash_code_execution_tool_result';
} & ResponseBashCodeExecutionToolResultBlock) | ({
    type?: 'text_editor_code_execution_tool_result';
} & ResponseTextEditorCodeExecutionToolResultBlock) | ({
    type?: 'tool_search_tool_result';
} & ResponseToolSearchToolResultBlock) | ({
    type?: 'container_upload';
} & ResponseContainerUploadBlock);

export type InputContentBlock = ({
    type?: 'text';
} & RequestTextBlock) | ({
    type?: 'image';
} & RequestImageBlock) | ({
    type?: 'document';
} & RequestDocumentBlock) | ({
    type?: 'search_result';
} & RequestSearchResultBlock) | ({
    type?: 'thinking';
} & RequestThinkingBlock) | ({
    type?: 'redacted_thinking';
} & RequestRedactedThinkingBlock) | ({
    type?: 'tool_use';
} & RequestToolUseBlock) | ({
    type?: 'tool_result';
} & RequestToolResultBlock) | ({
    type?: 'server_tool_use';
} & RequestServerToolUseBlock) | ({
    type?: 'web_search_tool_result';
} & RequestWebSearchToolResultBlock) | ({
    type?: 'web_fetch_tool_result';
} & RequestWebFetchToolResultBlock) | ({
    type?: 'code_execution_tool_result';
} & RequestCodeExecutionToolResultBlock) | ({
    type?: 'bash_code_execution_tool_result';
} & RequestBashCodeExecutionToolResultBlock) | ({
    type?: 'text_editor_code_execution_tool_result';
} & RequestTextEditorCodeExecutionToolResultBlock) | ({
    type?: 'tool_search_tool_result';
} & RequestToolSearchToolResultBlock) | ({
    type?: 'container_upload';
} & RequestContainerUploadBlock);

export type StopReason = 'end_turn' | 'max_tokens' | 'stop_sequence' | 'tool_use' | 'pause_turn' | 'refusal';

/**
 * The model that will complete your prompt.\n\nSee [models](https://docs.anthropic.com/en/docs/models-overview) for additional details and options.
 */
export type Model = string | 'claude-mythos-preview' | 'claude-opus-4-6' | 'claude-sonnet-4-6' | 'claude-haiku-4-5' | 'claude-haiku-4-5-20251001' | 'claude-opus-4-5' | 'claude-opus-4-5-20251101' | 'claude-sonnet-4-5' | 'claude-sonnet-4-5-20250929' | 'claude-opus-4-1' | 'claude-opus-4-1-20250805' | 'claude-opus-4-0' | 'claude-opus-4-20250514' | 'claude-sonnet-4-0' | 'claude-sonnet-4-20250514' | 'claude-3-haiku-20240307';

export type MessagesPostData = {
    body: CreateMessageParams;
    headers?: {
        /**
         * The version of the Claude API you want to use.
         *
         * Read more about versioning and our version history [here](https://docs.claude.com/en/api/versioning).
         */
        'anthropic-version'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/messages';
};

export type MessagesPostErrors = {
    /**
     * Error response.
     *
     * See our [errors documentation](https://docs.claude.com/en/api/errors) for more details.
     */
    '4XX': ErrorResponse;
};

export type MessagesPostError = MessagesPostErrors[keyof MessagesPostErrors];

export type MessagesPostResponses = {
    /**
     * Message object.
     */
    200: Message;
};

export type MessagesPostResponse = MessagesPostResponses[keyof MessagesPostResponses];

export type ModelsListData = {
    body?: never;
    headers?: {
        /**
         * The version of the Claude API you want to use.
         *
         * Read more about versioning and our version history [here](https://docs.claude.com/en/api/versioning).
         */
        'anthropic-version'?: string;
        /**
         * Your unique API key for authentication.
         *
         * This key is required in the header of all API requests, to authenticate your account and access Anthropic's services. Get your API key through the [Console](https://console.anthropic.com/settings/keys). Each key is scoped to a Workspace.
         */
        'x-api-key'?: string;
        /**
         * Optional header to specify the beta version(s) you want to use.
         *
         * To use multiple betas, use a comma separated list like `beta1,beta2` or specify the header multiple times for each beta.
         */
        'anthropic-beta'?: string;
    };
    path?: never;
    query?: {
        /**
         * ID of the object to use as a cursor for pagination. When provided, returns the page of results immediately before this object.
         */
        before_id?: string;
        /**
         * ID of the object to use as a cursor for pagination. When provided, returns the page of results immediately after this object.
         */
        after_id?: string;
        /**
         * Number of items to return per page.
         *
         * Defaults to `20`. Ranges from `1` to `1000`.
         */
        limit?: number;
    };
    url: '/v1/models';
};

export type ModelsListErrors = {
    /**
     * Error response.
     *
     * See our [errors documentation](https://docs.claude.com/en/api/errors) for more details.
     */
    '4XX': ErrorResponse;
};

export type ModelsListError = ModelsListErrors[keyof ModelsListErrors];

export type ModelsListResponses = {
    /**
     * Successful Response
     */
    200: ListResponseModelInfo;
};

export type ModelsListResponse = ModelsListResponses[keyof ModelsListResponses];

export type ModelsGetData = {
    body?: never;
    headers?: {
        /**
         * The version of the Claude API you want to use.
         *
         * Read more about versioning and our version history [here](https://docs.claude.com/en/api/versioning).
         */
        'anthropic-version'?: string;
        /**
         * Your unique API key for authentication.
         *
         * This key is required in the header of all API requests, to authenticate your account and access Anthropic's services. Get your API key through the [Console](https://console.anthropic.com/settings/keys). Each key is scoped to a Workspace.
         */
        'x-api-key'?: string;
        /**
         * Optional header to specify the beta version(s) you want to use.
         *
         * To use multiple betas, use a comma separated list like `beta1,beta2` or specify the header multiple times for each beta.
         */
        'anthropic-beta'?: string;
    };
    path: {
        /**
         * Model identifier or alias.
         */
        model_id: string;
    };
    query?: never;
    url: '/v1/models/{model_id}';
};

export type ModelsGetErrors = {
    /**
     * Error response.
     *
     * See our [errors documentation](https://docs.claude.com/en/api/errors) for more details.
     */
    '4XX': ErrorResponse;
};

export type ModelsGetError = ModelsGetErrors[keyof ModelsGetErrors];

export type ModelsGetResponses = {
    /**
     * Successful Response
     */
    200: ModelInfo;
};

export type ModelsGetResponse = ModelsGetResponses[keyof ModelsGetResponses];

export type ClientOptions = {
    baseUrl: 'https://api.anthropic.com' | (string & {});
};