name: 'Update Homebrew Formula'
description: 'Updates the Homebrew formula for the Bodhi app'
inputs:
  artifact_paths:
    description: 'The paths of the generated artifacts'
    required: true
  access_token:
    description: 'The GitHub access token to pull and write to the BodhiSearch/homebrew-apps repository'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Parse JSON and find DMG artifact path
      shell: bash
      id: dmg-artifact
      run: |
        DMG_ARTIFACT=$(jq -r '.[] | select(endswith(".dmg"))' <<< "$INPUT_ARTIFACT_PATHS")
        echo "DMG_ARTIFACT=${DMG_ARTIFACT}"
        echo "dmg_artifact=$DMG_ARTIFACT" >> $GITHUB_OUTPUT
        DMG_CHECKSUM=$(shasum -a 256 "${DMG_ARTIFACT}" | awk '{print $1}')
        echo "DMG_CHECKSUM=${DMG_CHECKSUM}"
        echo "dmg_checksum=$DMG_CHECKSUM" >> $GITHUB_OUTPUT
        DMG_FILENAME=$(sed 's/.*\///' <<< "$DMG_ARTIFACT")
        echo "dmg_filename=$DMG_FILENAME" >> $GITHUB_OUTPUT
      env:
        INPUT_ARTIFACT_PATHS: ${{ inputs.artifact_paths }}

    - name: Clone BodhiSearch/homebrew-apps
      shell: bash
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git clone https://x-access-token:${{ inputs.access_token }}@github.com/BodhiSearch/homebrew-apps.git

    - name: Update Bodhi formula
      shell: bash
      working-directory: homebrew-apps
      run: |
        ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/releases/download/${{ env.VERSION }}/${{ steps.dmg-artifact.outputs.dmg_filename }}"
        sed -i.bak "s|url .*|url \"${ARTIFACT_URL}\"|" bodhi.rb
        sed -i.bak "s|sha256 .*|sha256 \"${{ steps.dmg-artifact.outputs.dmg_checksum }}\"|" bodhi.rb
        rm bodhi.rb.bak
    - name: Commit and push changes
      shell: bash
      working-directory: homebrew-apps
      run: |
        RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        git add bodhi.rb
        git commit -m "[Github Bot][${{ env.VERSION }}][${{ env.TARGET }}] updated the homebrew with artifact\nurl: ${RUN_URL}"
        git push origin main
    - name: Clean up
      shell: bash
      run: |
        rm -rf homebrew-apps
