name: setup-rust-docker
description: setup rust and components for docker environments
inputs:
  platform:
    description: "Platform to build for"
    required: true
  target:
    description: "Target to build for"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: install dependencies (ubuntu only)
      shell: bash
      if: inputs.platform == 'ubuntu-latest'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          cmake \
          build-essential \
          ninja-build \
          libgomp1 \
          curl \
          git \
          libssl-dev \
          pkg-config
    - uses: Swatinem/rust-cache@v2
    - name: install Rust 1.93.0
      uses: dtolnay/rust-toolchain@1.93.0
      with:
        targets: ${{ inputs.target }}
        components: rustfmt,clippy,llvm-tools
