name: "Setup Android"
description: "Sets up Android with caching"

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: "17"
    - name: Cache Android SDK
      uses: actions/cache@v3
      with:
        path: |
          ~/.android/sdk
        key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-android-sdk-
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Install NDK
      shell: bash
      run: sdkmanager "ndk;27.1.12297006"
