mod auth_middleware;
mod direct_sse;
mod error;
mod fwd_sse;
pub mod interactive;
mod router_state;
mod routes;
mod routes_chat;
mod routes_dev;
mod routes_login;
mod routes_models;
mod routes_oai_models;
mod routes_ollama;
mod routes_proxy;
mod routes_setup;
mod routes_ui;
pub mod run;
pub mod serve;
#[allow(clippy::module_inception)]
mod server;
mod shutdown;
mod utils;
pub use crate::server::router_state::{RouterState, RouterStateFn};
pub use crate::server::routes::build_routes;
pub use crate::server::server::*;
pub use crate::server::shutdown::shutdown_signal;
pub use crate::server::utils::AxumRequestExt;
pub use auth_middleware::*;
pub use error::*;
