[package]
name = "bodhicore"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
async-openai = "0.20.0"
axum = "0.7.4"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.2", features = ["derive"] }
dialoguer = { version = "0.11.0", features = ["history"] }
dirs = "5.0.1"
futures-util = "0.3.30"
hf-hub = { version = "0.3.2", features = ["tokio"] }
humantime = "2.1.0"
include_dir = "0.7.3"
indicatif = { version = "0.17.8", features = ["tokio"] }
lazy_static = "1.4.0"
llama-server-bindings = { version = "0.1.0", path = "../llama-server-bindings" }
mime_guess = "2.0.4"
prettytable-rs = "0.10.0"
regex = "1.10.4"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.34"
tempfile = "3.10.1"
thiserror = "1.0.59"
tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = "0.1.15"
tower-http = { version = "0.5.2", features = ["trace", "cors"] }
tracing = { version = "0.1.40", features = ["async-await", "log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
ureq = "2.9.7"
walkdir = "2.5.0"
minijinja = "2.0.1"
derive-new = "0.6.0"
mockall = "0.12.1"
validator = { version = "0.18.1", features = ["derive"] }
once_cell = "1.19.0"
strum = { version = "0.26.2", features = ["derive"] }

[dev-dependencies]
anyhow_trace = "0.1.3"
ctor = "0.2.8"
dotenv = "0.15.0"
dircpy = "0.3.16"
http-body-util = "0.1.0"
lazy_static = "1.4.0"
mousse = "0.1.1"
rand = "0.8.5"
reqwest = "0.12.3"
rstest = "0.19.0"
serial_test = "3.1.1"
tempfile = "3.10.1"
tower = "0.4.13"
