/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'app-bindings.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./app-bindings.android-arm64.node')
          } else {
            nativeBinding = require('@bodhiapp/app-bindings-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'app-bindings.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./app-bindings.android-arm-eabi.node')
          } else {
            nativeBinding = require('@bodhiapp/app-bindings-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'app-bindings.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./app-bindings.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@bodhiapp/app-bindings-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'app-bindings.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./app-bindings.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@bodhiapp/app-bindings-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'app-bindings.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./app-bindings.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@bodhiapp/app-bindings-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'app-bindings.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./app-bindings.darwin-universal.node')
      } else {
        nativeBinding = require('@bodhiapp/app-bindings-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'app-bindings.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./app-bindings.darwin-x64.node')
          } else {
            nativeBinding = require('@bodhiapp/app-bindings-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'app-bindings.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./app-bindings.darwin-arm64.node')
          } else {
            nativeBinding = require('@bodhiapp/app-bindings-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'app-bindings.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./app-bindings.freebsd-x64.node')
      } else {
        nativeBinding = require('@bodhiapp/app-bindings-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'app-bindings.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./app-bindings.linux-x64-musl.node')
            } else {
              nativeBinding = require('@bodhiapp/app-bindings-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'app-bindings.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./app-bindings.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@bodhiapp/app-bindings-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'app-bindings.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./app-bindings.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@bodhiapp/app-bindings-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'app-bindings.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./app-bindings.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@bodhiapp/app-bindings-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'app-bindings.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./app-bindings.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@bodhiapp/app-bindings-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'app-bindings.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./app-bindings.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@bodhiapp/app-bindings-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'app-bindings.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./app-bindings.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@bodhiapp/app-bindings-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'app-bindings.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./app-bindings.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@bodhiapp/app-bindings-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'app-bindings.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./app-bindings.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@bodhiapp/app-bindings-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { createNapiAppOptions, setEnvVar, setAppSetting, setSystemSetting, setClientCredentials, setAppStatus, BODHI_HOME, BODHI_HOST, BODHI_PORT, BODHI_SCHEME, BODHI_LOG_LEVEL, BODHI_LOG_STDOUT, BODHI_LOGS, BODHI_ENV_TYPE, BODHI_APP_TYPE, BODHI_VERSION, BODHI_AUTH_URL, BODHI_AUTH_REALM, BODHI_ENCRYPTION_KEY, BODHI_EXEC_LOOKUP_PATH, BODHI_EXEC_VARIANT, BODHI_KEEP_ALIVE_SECS, HF_HOME, DEFAULT_HOST, DEFAULT_PORT, BodhiServer } = nativeBinding

module.exports.createNapiAppOptions = createNapiAppOptions
module.exports.setEnvVar = setEnvVar
module.exports.setAppSetting = setAppSetting
module.exports.setSystemSetting = setSystemSetting
module.exports.setClientCredentials = setClientCredentials
module.exports.setAppStatus = setAppStatus
module.exports.BODHI_HOME = BODHI_HOME
module.exports.BODHI_HOST = BODHI_HOST
module.exports.BODHI_PORT = BODHI_PORT
module.exports.BODHI_SCHEME = BODHI_SCHEME
module.exports.BODHI_LOG_LEVEL = BODHI_LOG_LEVEL
module.exports.BODHI_LOG_STDOUT = BODHI_LOG_STDOUT
module.exports.BODHI_LOGS = BODHI_LOGS
module.exports.BODHI_ENV_TYPE = BODHI_ENV_TYPE
module.exports.BODHI_APP_TYPE = BODHI_APP_TYPE
module.exports.BODHI_VERSION = BODHI_VERSION
module.exports.BODHI_AUTH_URL = BODHI_AUTH_URL
module.exports.BODHI_AUTH_REALM = BODHI_AUTH_REALM
module.exports.BODHI_ENCRYPTION_KEY = BODHI_ENCRYPTION_KEY
module.exports.BODHI_EXEC_LOOKUP_PATH = BODHI_EXEC_LOOKUP_PATH
module.exports.BODHI_EXEC_VARIANT = BODHI_EXEC_VARIANT
module.exports.BODHI_KEEP_ALIVE_SECS = BODHI_KEEP_ALIVE_SECS
module.exports.HF_HOME = HF_HOME
module.exports.DEFAULT_HOST = DEFAULT_HOST
module.exports.DEFAULT_PORT = DEFAULT_PORT
module.exports.BodhiServer = BodhiServer
