name: setup-playwright
description: Setup Playwright and install browsers with caching
inputs:
  platform:
    description: "Platform to build for"
    required: true
  working-directory:
    description: "Working directory for Playwright"
    required: false
    default: "crates/lib_bodhiserver_napi"

runs:
  using: composite
  steps:
    - name: Setup Node and npm
      uses: ./.github/actions/setup-node
      with:
        platform: ${{ inputs.platform }}

    - name: Install Playwright dependencies (Windows)
      if: inputs.platform == 'windows-latest'
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      run: npm ci

    - name: Install Playwright dependencies (Unix)
      if: inputs.platform != 'windows-latest'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci

    - name: Get Playwright version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Ensure package.json exists and get Playwright version
        if [ -f "package.json" ]; then
          PLAYWRIGHT_VERSION=$(npm list @playwright/test --depth=0 --json 2>/dev/null | jq -r '.dependencies["@playwright/test"].version // empty')
          if [ -z "$PLAYWRIGHT_VERSION" ] || [ "$PLAYWRIGHT_VERSION" = "null" ]; then
            # Fallback to reading from package.json
            PLAYWRIGHT_VERSION=$(node -p "require('./package.json').devDependencies['@playwright/test'] || require('./package.json').dependencies['@playwright/test']" 2>/dev/null || echo "1.57.0")
          fi
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
        else
          echo "PLAYWRIGHT_VERSION=1.57.0" >> $GITHUB_ENV
        fi

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          %USERPROFILE%\AppData\Local\ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright browsers (Windows)
      if: inputs.platform == 'windows-latest' && steps.playwright-cache.outputs.cache-hit != 'true'
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      run: npx playwright install --with-deps chromium

    - name: Install Playwright browsers (Unix)
      if: inputs.platform != 'windows-latest' && steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Pre-install Ubuntu 24.04 compatibility packages to avoid Playwright dependency issues
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          UBUNTU_VERSION=$(lsb_release -rs 2>/dev/null || echo "22.04")
          if [[ "$UBUNTU_VERSION" == "24.04" ]]; then
            echo "Ubuntu 24.04 detected, pre-installing compatibility packages..."
            sudo apt-get update
            # Install the specific packages that are missing/renamed in Ubuntu 24.04
            sudo apt-get install -y \
              libasound2t64 \
              libicu74 \
              libffi8 \
              libx264-164
          fi
        fi
        npx playwright install --with-deps chromium 