name: Command line Release Flow

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish-cmd:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          # - platform: "macos-latest" # for Intel based macs.
          #   args: "--target x86_64-apple-darwin"
          # - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
          #   args: ""
          # - platform: "windows-latest"
          #   args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup
        uses: ./.github/actions/setup
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Set VERSION environment variable
        run: |
          if [[ "${GITHUB_REF}" =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            DATE=$(date +%Y%m%d)
            GITSHA=$(git rev-parse --short=8 HEAD)
            echo "VERSION=0.0.1-${DATE}-${GITSHA}" >> $GITHUB_ENV
          fi
      - name: build the commandline
        working-directory: app/bodhi
        run: |
          cargo build --release --bin bodhicli ${{ matrix.args }}
      - name: rename the executable
        run: |
          mv target/release/bodhicli target/release/bodhi
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Bodhi CLI Release ${{ env.VERSION }}
          draft: false
          prerelease: true
          files: target/release/bodhi
