name: App Release Flow

on:
  push:
    # branches:
    #   - main
    tags:
      - "v*"
  workflow_dispatch:

env:
  CI: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.version }}
      TAG_BUILD: ${{ steps.get_version.outputs.tag_build }}
      RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}
    steps:
      - uses: actions/checkout@v4
      - name: Set VERSION environment variable
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "TAG_BUILD=true" >> $GITHUB_OUTPUT
          else
            DATE=$(date +%Y%m%d)
            GITSHA=$(git rev-parse --short=8 HEAD)
            echo "VERSION=0.0.0-${DATE}-${GITSHA}" >> $GITHUB_OUTPUT
            echo "TAG_BUILD=false" >> $GITHUB_OUTPUT
          fi
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ steps.get_version.outputs.version }}'
          release_name: 'Bodhi v${{ steps.get_version.outputs.version }}'
          body: "See the assets to download this version and install."
          draft: false
          prerelease: true

  publish:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            target: aarch64-apple-darwin
            llama_cpp_build_flags: "-DLLAMA_METAL_EMBED_LIBRARY=ON"
          # - platform: "macos-latest" # for Intel based macs.
          #   args: "--target x86_64-apple-darwin"
          # - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
          #   args: ""
          # - platform: "windows-latest"
          #   args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - name: envs
        run: |
          echo TARGET=${{ matrix.target }} >> $GITHUB_ENV
          echo VERSION=${{ needs.create-release.outputs.VERSION  }} >> $GITHUB_ENV
          echo TAG_BUILD=${{ needs.create-release.outputs.TAG_BUILD  }} >> $GITHUB_ENV
          echo RELEASE_UPLOAD_ID=${{ needs.create-release.outputs.RELEASE_UPLOAD_ID  }} >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: setup
        uses: ./.github/actions/setup
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: llama_cpp
        uses: ./.github/actions/llama_cpp
        with:
          LLAMA_CPP_BUILD_FLAGS: ${{ matrix.llama_cpp_build_flags }}
      - name: clean
        run: |
          cargo clean -p llama-server-bindings
          cargo clean -p bodhi
      - name: build llama-server-bindings
        run: |
          cargo build -p llama-server-bindings --target ${{ matrix.target }}
      - name: tauri-action
        id: tauri-action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_API_BASE_URL: "/"
        with:
          projectPath: app
          distPath: app/out
          appName: Bodhi
          appVersion: ${{ env.VERSION }}
          releaseId: ${{ env.RELEASE_UPLOAD_ID }}
          args: "--target ${{ matrix.target }}"
      - name: Update Homebrew Formula
        if: matrix.target == 'aarch64-apple-darwin' && env.TAG_BUILD == 'true'
        uses: ./.github/actions/homebrew
        with:
          access_token: ${{ secrets.GH_PAT }}
          artifact_paths: ${{ steps.tauri-action.outputs.artifactPaths }}
